services:
  - type: web
    name: exam-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gthread --workers 1 --threads 12 --timeout 0 server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
